examples/complete-ecs/main.tf
remove the dependency of hard coded region and available zones in examples.
Normally we set `AWS_REGION` or `AWS_DEFAULT_REGION` environment variable, or set `region` in aws credentials file already. 
this PR removes the dependency of hard coded region and available zones, so end users can directly run the example without any codes to be updated in examples.
No, just a change in example
but if the region has three or four available zone, it would create more resources than before. 
If you do want to limit the number of AZs to 2 only, I can adjust the code to:
```
azs             = [data.aws_availability_zones.available.names[0], data.aws_availability_zones.available.names[1]]
```
```
terraform init
terraform plan
terraform apply
```
=> fix: Remove the dependency of hard coded region and availability zones

examples/complete-ecs/main.tf
with original setting, nat gateway is disable, we have no chance to know why the ec2 instance can't be added to ECS cluster automatically, because when the ec2 instance started, it has a yum update job failed (no internet access, blocked and failed)
second, the default autoscaling group is set to 0 for desired size, it makes me crazy why I can't see it in ECS directly. 
This PR fixed both problems 
This PR fixed both problems described above.
No, it is example change.
```
terraform init
terraform plan
terraform apply
```
=> fix: make the example workable

.pre-commit-config.yaml, README.md, examples/complete-ecs/README.md, examples/complete-ecs/main.tf, examples/complete-ecs/service-hello-world/main.tf, main.tf, modules/ecs-instance-profile/main.tf, variables.tf
Add container insights settings + update pre-commit hook version
per: 
https://www.terraform.io/docs/providers/aws/r/ecs_cluster.html#setting
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS.html
=> feat: Add container insights

modules/ecs-instance-profile/main.tf, modules/ecs-instance-profile/variables.tf
Allows adding custom tags to ECS instance profile role.
We have a policy to tag all taggable AWS resources in the company. It would be great if we could tag this role as well.
No breaking changes, as has an empty map default.
The change has been tested by referencing a fork repo with this change and applying.
=> Add tags to ECS instance profile role

.gitignore, README.md, examples/complete-ecs/main.tf, examples/complete-ecs/service-hello-world/versions.tf, main.tf, variables.tf
As the description of the variable says the default can be one or more. Also, the ECS supports multiple defaults, the changes have been made.
It allows to add multiple default capacity provider strategy for the ECS services.
I made the changes on my local module and applied `terraform plan`.
=> fix: Converting type of `default_capacity_provider_strategy` from map to list

.gitignore, .pre-commit-config.yaml, README.md, examples/complete-ecs/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
=> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete-ecs/README.md, examples/complete-ecs/versions.tf, modules/ecs-instance-profile/versions.tf, versions.tf
- correct documentation based on update by `terraform_docs`
- bump min supported version due to types unsupported on current
- static checks are currently failing due to docs mis-match
- No
- static checks
=> fix: correct documentation based on update by `terraform_docs`

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete-ecs/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
=> chore: update documentation and pin `terraform_docs` version to avoid future changes

examples/complete-ecs/main.tf
Executing `terraform apply` in the example-complete folder you will receive a message error likes
```
╷
│ Error: One of `launch_configuration`, `launch_template`, or `mixed_instances_policy` must be set for an Auto Scaling Group
│
│   with module.asg.aws_autoscaling_group.this[0],
│   on .terraform/modules/asg/main.tf line 309, in resource "aws_autoscaling_group" "this":
│  309: resource "aws_autoscaling_group" "this" {
│
╵
```
This commit will solve the message error. 
Consulting [Auto Scaling Module Reference](https://github.com/terraform-aws-modules/terraform-aws-autoscaling#conditional-creation) I have used conditional creation for autoscaling group and launch configuration
There aren't breaking changes
I have tested and validated these changes using executing `terraform apply` in …
=> fix: 'One of launch_configuration, launch_template, or mixed_instance must be set for an Auto Scaling Group'

.pre-commit-config.yaml, modules/ecs-instance-profile/README.md, modules/ecs-instance-profile/main.tf
Modified `ec2_profile` module to support AWS GovCloud partition in the arn
I am currently working in GovCloud and wanted to use this well executed module. The change is minor and would benefit others.
No, this does not break compatibility.
I ran the `complete-ecs` example module in a regular us-east-1 AWS account and a us-gov-west-1 AWS GovCloud account.
=> feat: Add GovCloud support

examples/complete-ecs/main.tf
The Complete ECS Example don't work. Don't configure the IAM Role in ASG.
This is because the example uses launch configuration and the variable iam_instance_profile_arn.
The variable iam_instance_profile_arn should be use with launch template.
With launch configurations should use the variable iam_instance_profile_name.
fixes #42
none
=> fix: Complete ECS example (IAM role not configured in ASG)

README.md, examples/complete-ecs/README.md, examples/complete-ecs/versions.tf, main.tf, versions.tf
Add an [aws_ecs_cluster_capacity_providers](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster_capacity_providers) resource.
AWS provider v4 has deprecated declaring the capacity provider in the `aws_ecs_cluster` resource.
Fixes https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/54.
This resource was introduced in v3.74.0 so will break anything using an earlier version.
See https://github.com/hashicorp/terraform-provider-aws/pull/22672.
Tested using an existing deployment.
=> feat: Add aws_ecs_cluster_capacity_providers resource

.pre-commit-config.yaml, main.tf
- Add empty map to `execute_command_configuration` to avoid plugin crash from interface conversion
- Closes #61
- No
=> fix: Add empty map to `execute_command_configuration` to avoid plugin crash from interface conversion

examples/complete/main.tf
The goal of this PR is to resolve EC2 instances not being able to successfully join the ECS cluster produced by `examples/complete/` by switching `enable_nat_gateway` from `false` to `true`.
This PR resolves #63
The motivation is to ensure the examples can successfully bootstrap an ECS cluster and place tasks on the newly provisioned EC2 instances.
None.
=> fix: Complete example EC2 instance cluster joining issue

.pre-commit-config.yaml, README.md
- Correct examples in README to correct `name` -> `cluster_name`
- Docs currently reference `name` but it should be `cluster_name`
- No
- [x ] I have executed `pre-commit run -a` on my pull request
=> docs: Correct examples in README to correct `name` -> `cluster_name`

.pre-commit-config.yaml, README.md, examples/complete/main.tf, main.tf, variables.tf
- Allow for both Fargate and EC2/Autoscaling capacity providers in same cluster
- Closes #68
- Allows users to use both Fargate and EC2/Autoscaling capacity providers within the same cluster
- No; if users are currently using EC2/Autoscaling as their default capacity provider strategy, they will want to set `default_capacity_provider_use_fargate = false`
=> fix: Allow for both Fargate and EC2/Autoscaling capacity providers in same cluster

.pre-commit-config.yaml, examples/complete/README.md, examples/complete/main.tf, examples/ec2-autoscaling/main.tf, examples/fargate/README.md, examples/fargate/main.tf
- Add example showing `nonsensitive()` for pulling images from SSM parameter
- Add spot instance usage to examples
- Demonstrates how to use SSM parameter data source in container definition without making the entire object + task definition outputs sensitive 
- Resolves #77
=> docs: Add example showing `nonsensitive()` for pulling images from SSM parameter, add spot instance usage to examples

examples/ec2-autoscaling/main.tf, modules/service/main.tf
- Ensure that launch type is not specified when a capacity provider strategy is set on a service
- Update EC2 autoscaling example to show use of capacity providers created
- You cannot set both a launch type and capacity provider strategy on a service; its one or the other. By default the module is designed around Fargate so this is the default launch type. However, the launch type should be `null` when a capacity provider strategy is provided
- Currently the EC2 example incorrectly shows capacity provider strategy usage. This PR corrects that
- No
=> fix: Ensure that launch type is not specified when a capacity provider strategy is set on a service

modules/container-definition/main.tf
If we pass `enable_cloudwatch_logging = false` on a service `container_definitions` section, it will generate this error below:
```
│ Error: creating ECS Task Definition (my-service): InvalidParameter: 1 validation error(s) found.
│ - missing required field, RegisterTaskDefinitionInput.ContainerDefinitions[0].LogConfiguration.LogDriver.
│ 
│ 
│   with module.ecs.module.service["my-container"].aws_ecs_task_definition.this[0],
│   on ../../modules/aws-compute-ecs/modules/service/main.tf line 608, in resource "aws_ecs_task_definition" "this":
│  608: resource "aws_ecs_task_definition" "this" {
```
This behavior happens because in the planning phase the `logConfiguration` is computed as `{}`, which is an invalid configuration when posting on AWS API.
My `plan` of a just imported resource is: …
=> fix: Missing field LogConfiguration.LogDriver error when enable_cloudwatch_logging is false

.pre-commit-config.yaml, examples/complete/README.md, examples/complete/main.tf, examples/ec2-autoscaling/README.md, examples/ec2-autoscaling/main.tf, examples/fargate/README.md, examples/fargate/main.tf, modules/container-definition/main.tf, modules/service/main.tf
- Add default values for attributes that are showing up in plans and causing unnecessary diffs
- Resolves #99
- No
=> fix: Add default values for attributes that are showing up in plans and causing unnecessary diffs

.pre-commit-config.yaml, modules/service/README.md, modules/service/variables.tf
- Correct `wait_until_stable_timeout` variable type
- Resolves #104
- No
=> fix: Correct `wait_until_stable_timeout` variable type

modules/service/outputs.tf
- Add the external resource equivalents to the outputs as the fallback value
- When chaining/embedding this module, its easier if the ARNs of resources created outside of the module that are used in place of what the module would create are provided in the outputs. 
- No
=> feat: Add the external resource equivalents to the outputs as the fallback value

modules/service/main.tf
Add condition for creating container definition
Have a single terraform for dev, stage, and production, to dev I don't need all containers.
No
I have tested.
=> feat: Add create option for container definition

modules/service/main.tf
Add the `tags`variable into the `aws_appautoscaling_target`. 
I'm using this module to setup an ECS Service and our checkov complained about missing tags in the `aws_appautoscaling_target`. This PR has the goal to add the tags to this resource.
None.
=> fix: Add missing tag variable in autoscaling target resource

examples/fargate/main.tf, modules/container-definition/main.tf
- Allow setting `linux_parameters` without inconsistent left/right error
- Resolves #134
- No
=> fix: Allow setting `linux_parameters` without inconsistent left/right error

.pre-commit-config.yaml, README.md, examples/complete/README.md, examples/complete/versions.tf, examples/ec2-autoscaling/README.md, examples/ec2-autoscaling/versions.tf, examples/fargate/README.md, examples/fargate/versions.tf, modules/cluster/README.md, modules/cluster/versions.tf, modules/container-definition/README.md, modules/container-definition/versions.tf, modules/service/README.md, modules/service/versions.tf, versions.tf
- Bump MSV of AWS provider to support AppAutoscaling target tags
- Context https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/135#issuecomment-1828502982
- [v4.66.0 PR to add tags](https://github.com/hashicorp/terraform-provider-aws/pull/30172)
- [v4.66.1 PR to fix tags](https://github.com/hashicorp/terraform-provider-aws/pull/31214)
- No
=> fix: Bump MSV of AWS provider to support AppAutoscaling target tags

examples/complete/main.tf, modules/container-definition/main.tf
The current PR explicitly adds the `interval`,`retries`, and `timeout` parameters to the `healthCheck` block when they are not supplied to prevent mismatches between the Terraform state and AWS, which results in a new task revision during each `terraform apply`.
**Note:** The default values are taken from the official [documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_HealthCheck.html#API_HealthCheck_Contents).
- Resolves #148 
No breaking changes
=> fix: Adding a `health_check` generates a new task definition revision on every `terraform apply`

examples/fargate/main.tf, modules/service/README.md, modules/service/main.tf, modules/service/variables.tf, wrappers/service/main.tf
Add the variable service_tags in the service module to configure individually when using the module directly
When using the service module directly, there is no option to set a specific tag for the service
```
+ resource "aws_ecs_service" "this" {
+ cluster                            = (known after apply)
+ deployment_maximum_percent         = 200
+ deployment_minimum_healthy_percent = 66
+ desired_count                      = 1
+ enable_ecs_managed_tags            = true
+ enable_execute_command             = true
+ force_new_deployment               = true
+ iam_role                           = (known after apply)
+ id                                 = (known after apply)
+ launch_type                        = "FARGATE"
+ name                               = "ex-fargate"
+ …
```
=> feat: Add var service_tags

.pre-commit-config.yaml, README.md, examples/complete/README.md, examples/complete/versions.tf, examples/ec2-autoscaling/README.md, examples/ec2-autoscaling/main.tf, examples/ec2-autoscaling/versions.tf, examples/fargate/README.md, examples/fargate/versions.tf, modules/cluster/README.md, modules/cluster/main.tf, modules/cluster/versions.tf, modules/container-definition/README.md, modules/container-definition/versions.tf, modules/service/README.md, modules/service/versions.tf, versions.tf
Support of `managed_draining` argument at `auto_scaling_group_provider` block of  `aws_ecs_capacity_provider` resource introduced by
- [v5.34.0 of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/v5.34.0/CHANGELOG.md).
- https://github.com/hashicorp/terraform-provider-aws/pull/35421
- Resolves https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/156
:warning: Minimal required AWS provider version is `>=5.34.0`
For already created ECS ASG capacity provider:
- config
```HCL
module "ecs_cluster" {
source = "../../../../../../open-source/terraform-aws-ecs/modules/cluster"
cluster_name = local.ecs_cluster_name
default_capacity_provider_use_fargate = false
autoscaling_capacity_providers = {
for k, v in module.asg_ecs : …
```
=> feat: Support `managed_draining` argument at `aws_ecs_capacity_provider`

README.md, main.tf, modules/cluster/README.md, modules/cluster/main.tf, modules/cluster/outputs.tf, modules/cluster/variables.tf, modules/container-definition/README.md, modules/container-definition/main.tf, modules/container-definition/outputs.tf, modules/container-definition/variables.tf, outputs.tf, variables.tf, wrappers/cluster/main.tf, wrappers/container-definition/main.tf, wrappers/main.tf
The possibility to define a **custom** AWS CloudWatch LogGroup name instead of a pre-defined pattern at the module.
Previously, it was impossible to define the custom name of CW LogGroup while creating a group with the modules.
No.
- config
```HCL
module "ecs_cluster" {
source = "../../../../../../open-source/terraform-aws-ecs/modules/cluster"
cloudwatch_log_group_name = "/aws/ecs/custom-cluster-test"
```
- `terraform plan`
```bash
-/+ resource "aws_cloudwatch_log_group" "this" {
~ arn               = "arn:aws:logs:xxx:xxx:log-group:/aws/ecs/xxx" -> (known after apply)
...
~ name              = "/aws/ecs/xxx" -> "/aws/ecs/custom-cluster-test" # forces replacement
...
}
```
- config
```HCL
module "ecs_cluster" {
```
- `terraform plan`
```bash
No changes. Your infrastructure matches the …
```
=> feat: Add support for cluster and container definition custom CloudWatch log group names

examples/complete/main.tf, examples/ec2-autoscaling/main.tf, modules/service/main.tf
Fix the passing of the custom CloudWatch log group name through the `service` module to the  `container-definition` one introduced in https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/160.
To have the ability to pass custom CloudWatch log group name from the `service` module.
=> fix: Pass CloudWatch log group name from the service module to the container definition module

examples/ec2-autoscaling/main.tf
Fix the example with a custom CloudWatch log group name because `log_configuration.options` override during the merge operation as Terraform doesn't perform a deep merge of nested maps.
Fixes https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/173
=> docs: Fix example as Terraform performs shallow merge of nested maps

.pre-commit-config.yaml, modules/service/main.tf
The Security Group in ECS Service is missing the "Name" tag.
=> fix: Add missing `Name` tag to service security group

.pre-commit-config.yaml, examples/fargate/README.md, examples/fargate/main.tf, examples/fargate/outputs.tf, main.tf, modules/container-definition/main.tf, modules/service/README.md, modules/service/main.tf, modules/service/outputs.tf, modules/service/variables.tf, wrappers/service/main.tf
The new `create_service_resource` variable controls whether a `service` resource should be created (which is `true` by default) allowing skipping creation of the service when it's not required.
- Resolves #162
No breaking changes were introduced in the PR.
=> feat: Allow disabling service creation to support creating just a task definition

.pre-commit-config.yaml, modules/service/main.tf, wrappers/cluster/versions.tf, wrappers/container-definition/versions.tf, wrappers/service/versions.tf, wrappers/versions.tf
- Make service, task, and task sets wait for their respective policy attachment to ensure permissions are available
- Resolves #200
- No
=> fix: Make service, task, and task sets wait for their respective policy attachment to ensure permissions are available

.pre-commit-config.yaml, modules/service/main.tf, wrappers/cluster/versions.tf, wrappers/container-definition/versions.tf, wrappers/service/versions.tf, wrappers/versions.tf
I added support for customized_metric_specification when using the `metrics` block, instead of using the current setup: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy.html#create-target-tracking-scaling-policy-using-metric-math
This change adds support for metric math in queries, which is useful for things like SQS-queue size based autoscaling
No, since you can still specify a metric the old way
There was no example to test against, but the example code would look like so:
```
autoscaling_policies = {
"scale_consumer" = {
policy_type = "TargetTrackingScaling"
target_tracking_scaling_policy_configuration = {
customized_metric_specification = {
metrics = [{
id = "m1"
label = "Get the queue size"
return_data = false
metric_stat = {
metric = …
```
=> feat: Add support for custom metric queries in customized_metric_spec

.pre-commit-config.yaml, main.tf
Missing pid_mod.
Missing  pid_mode in main.tf.  
Was not able to set:
pid_mode                 = "task"
No
=> fix: Add missing `pid_mode` to root module

modules/service/main.tf
When configuring `modules/service` to disable service creation with parameters:
```
create         = false
create_service = false
```
The following error happens
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Invalid function argument
│ 
│   on .terraform/modules/service/main.tf line 1206, in locals:
│ 1206:   cluster_name = element(split("/", var.cluster_arn), 1)
│     ├────────────────
│     │ while calling split(separator, str)
│     │ var.cluster_arn is null
│ 
│ Invalid value for "str" parameter: argument must not be null.
╵
```
This change make it works in with create true/false without error.
=> fix: Local `cluster_name` error when `var.cluster_arn` is empty

examples/ec2-autoscaling/main.tf, main.tf, modules/service/main.tf
@bryantbiggs sorry for the iteration, but #223 merged in before I could push another fix to the infra role logic.
`volume_configuration` variable is defaulted to `{}`, which the `null` check will never work.
=> fix: Correct logic for local `needs_infrastructure_iam_role` check

.github/workflows/pr-title.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete/README.md, examples/ec2-autoscaling/README.md, examples/fargate/README.md, modules/cluster/README.md, modules/container-definition/README.md, modules/service/README.md
- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No
=> fix: Update CI workflow versions to latest

examples/fargate/main.tf
I think that create_service should be set to false for and standalone task  (see #176).
Looks like a regression bug of #188
**Please note that this change not has been tested.
Is a quick fix using the GitHub web interface, feel free to close the PR and consider it as invalid.**
pre-commit run -a was executed and detect changes on README,md an LICENSE by terraform_docs, looks like false positives due my environment
=> docs: Create_service false for stand alone task on Fargate Sample

modules/service/variables.tf
In service/main.tf it is used a plural tag_specifications name for the attribute
In the service it is used reference for a plural tag_specifications but in variables.tf the variable name is singular tag_specifications, this makes the deployment to break, after changing to plural it works again.
In file modules/service/variables.tf we have singular tag_specification
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/bf5bdcd4403951831d27177d0f44c3ff3d2599aa/modules/service/variables.tf#L286
But in modules/service/main.tf we have plural tag_specifications
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/bf5bdcd4403951831d27177d0f44c3ff3d2599aa/modules/service/main.tf#L245
```
dynamic "tag_specifications" {
for_each = managed_ebs_volume.value.tag_specifications != …
```
=> chore: Update variable name to tag_specifications

.pre-commit-config.yaml, modules/service/main.tf
This fixes the issue specifically with the `ignore_task_definition` service type.
This change ensures that ECS service tags are properly applied when using the `ignore_task_definition` service configuration. Previously, only `var.tags` were used, which caused `var.service_tags` to be ignored entirely for this resource.
The following change was made:
```hcl
- tags = var.tags
+ tags = merge(var.tags, var.service_tags)
```
Currently, when using `ignore_task_definition = true`, the ECS service resource does not receive any tags defined in `var.service_tags`. 
There is no open issue for this, but the fix is straightforward and consistent with tagging patterns used elsewhere in the module.
No breaking changes.
in locals :`region = "us-east-1"`,
in module "ecs_service": …
=> fix: Ensure both ECS service definitions use the same settings/configurations

modules/cluster/main.tf, modules/container-definition/main.tf, modules/service/main.tf
- Pass missing `versionConsistency` argument to `service` sub-module
- Correct IAM policy statement `conditions` to `condition`
- Resolves #301
- Resolves #302
- No
=> fix: Pass missing `versionConsistency` argument, correct `conditions` to `condition`

modules/cluster/README.md
1.  Following cluster submodule's variables were renamed by this [commit](https://github.com/terraform-aws-modules/terraform-aws-ecs/blame/master/modules/cluster/variables.tf#L52)
```diff
- cluster_name
+ name
- cluster_configuration
+ configuration
```
2. But [cluster  module's example code](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/modules/cluster/README.md?plain=1#L22) on README is still using old name variables.
3. This PR update these example code
just want to put correct example code for cluster submodule for the reader.
No, this PR only include updates for readme
=> docs: Update for cluster submodule example code which use renamed vars

examples/complete/main.tf, modules/service/main.tf
This removes an unnecessary for_each and dynamic setting for `issuer_cert_authority` which is a required setting when using tls.
This fixes a bug:
```
Error: Unsupported attribute
on .terraform/modules/web_ecs_service/modules/service/main.tf line 257, in resource "aws_ecs_service" "this":
aws_pca_authority_arn = issuer_cert_authority.value.aws_pca_authority_arn
issuer_cert_authority.value is "arn:aws:acm-pca:us-east-2:SNIP:certificate-authority/SNIP"
Can't access attributes on a primitive-typed value (string).
```
No breaking changes.
=> fix: Correct loop extraction logic for `tls.issuer_cert_authority`

README.md
When running as the example in README I got 
```
attribute "service_connect_configuration": attribute "service": list of object required.
```
Fixing that
=> docs: Correct example usage of `service_connect_configuration.service` in README
